data:
  path: Data/breastCancer.csv
  target: diagnosis
  label_map: {B: 0, M: 1}
  # Optional explicit categorical columns; will auto-detect if missing
  categorical: [gender]

splits:
  test_size: 0.2
  cv_folds: 5
  seeds: [42, 1337, 2020, 7, 99]

calibration:
  enabled: true
  method: sigmoid  # 'sigmoid' (Platt) or 'isotonic'
  cv: 5

models:
  rf:
    n_estimators: [300]
    max_depth: [null, 8, 12]
    max_features: [sqrt, 0.5]
    min_samples_split: [2, 5]
  lr:
    C: [0.1, 1.0, 10.0]
  svc:
    C: [1.0, 10.0]
    gamma: [0.01, 0.1]
  dt:
    max_depth: [null, 5, 8, 12]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 5]
    ccp_alpha: [0.0, 0.001]

metrics: [roc_auc, average_precision, f1_macro, accuracy, brier]

ensembles:
  soft_vote: true
  stacking: true
  meta:
    C: 1.0

plotting:
  enabled: true

